<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>tbl</string>
		<string>top</string>
		<string>tst</string>
	</array>
	<key>name</key>
	<string>ChatScript</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(\^(argument|callstack|clearmatch|command|end|eval|loop|fail|load|match|matches|nofail|notnull|norejoinder|nottrace|return|addcontext|clearcontext|incontext|authorized|csboot|csshutdown|cs_reboot|cs_topic_enter|cs_topic_exit))(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.ChatScript</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Built-in functions (control flow)</string>
			<key>contentName</key>
			<string>variable.ChatScript</string>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>variable.ChatScript</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>System variables (date &amp; time &amp; numbers)</string>
			<key>match</key>
			<string>(\%)(date|day|daynumber|fulltime|hour|timenumbers|leapyear|daylightsavings|minute|month|monthname|second|volleytime|time|week|year|zulutime)</string>
			<key>name</key>
			<string>constant.numeric.ChatScript</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>System variables (chatbot output)</string>
			<key>match</key>
			<string>(\%)(inputrejoinder|lastoutput|lastquestion|outputrejoinder|response|all|crosstalk|document|fact|freetext|freedict|freefact|freeword|maxmatchvariables|maxfactsets|host|regression|server|rule|topic|actualtopic|trace|httpresponse|pid|restart|timeout)</string>
			<key>name</key>
			<string>constant.numeric.ChatScript</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>System variables (build data)</string>
			<key>match</key>
			<string>(\%)(dict|engine|os|script|version)</string>
			<key>name</key>
			<string>constant.numeric.ChatScript</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Interchange variables</string>
			<key>match</key>
			<string>(\$)(cs_outputchoice|cs_afterreset|cs_beforereset|cs_token|cs_response|cs_jsontimeout|cs_crashmsg|cs_abstract|cs_looplimit|cs_trace|cs_control_pre|cs_prepass|cs_control_main|cs_control_post|cs_usermessagelimit|cs_externaltag|botprompt|userprompt|cs_language|cs_wildcardseparator|cs_userfactlimit|cs_randindex|cs_utcoffset|cs_bot|cs_login|cs_fullfloat|cs_botid|cs_numbers|cs_topicretrylimit|cs_saveusedjson|cs_proxycredentials|cs_proxyserver|cs_proxymethod|\$db_error|\$findtext_start|\$findtext_word|\$tcpopen_error|\$document|\$csmatch_start|\$csmatch_end|\$topic_retry_limit_exceeded)</string>
			<key>name</key>
			<string>constant.numeric.ChatScript</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.numeric.ChatScript</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.language.ChatScript</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Input capture variables</string>
			<key>match</key>
			<string>(\s*)(\'?)(_\d+)</string>
			<key>name</key>
			<string>constant.language.ChatScript</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Position variable</string>
			<key>match</key>
			<string>@[\w,\d,\-,_]+[\-,\+]?</string>
			<key>name</key>
			<string>constant.language.ChatScript</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>User transient variables</string>
			<key>match</key>
			<string>\$\$\w+</string>
			<key>name</key>
			<string>variable.parameter.ChatScript</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>User variables</string>
			<key>match</key>
			<string>\$[a-z,A-Z,\d,\-,_]+</string>
			<key>name</key>
			<string>variable.parameter.ChatScript∫∫</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>((if|else\sif)(?:\s*)(?=\(+))|(else\s*)(?=\{|\n)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.numeric.ChatScript</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.numeric.ChatScript</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.numeric.ChatScript</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Execution flow</string>
			<key>end</key>
			<string>\)</string>
			<key>name</key>
			<string>none.ChatScript</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\!|==|\s(AND|OR)\s|&gt;=|&lt;=|\!=|&gt;|&lt;|\?)</string>
					<key>name</key>
					<string>keyword.numeric.ChatScript</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>Integers</string>
			<key>match</key>
			<string>\d+</string>
			<key>name</key>
			<string>constant.numeric.ChatScript</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Boolean &amp; state</string>
			<key>match</key>
			<string>\s(null|true|false)(?![\w,\d])</string>
			<key>name</key>
			<string>constant.numeric.ChatScript</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Assigment</string>
			<key>match</key>
			<string>(?!\s)(=(?!=)|\+=|-=|\*=|/=|\%=|\*\*=|&lt;&lt;=|&gt;&gt;=|&gt;&gt;&gt;=|&lt;&lt;|&gt;&gt;|&amp;=|\^=|\|=|\|)</string>
			<key>name</key>
			<string>keyword.numeric.ChatScript</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Operators</string>
			<key>match</key>
			<string>(?:\(|\s+)(\-|\+|/|\*|\s%\s)</string>
			<key>name</key>
			<string>keyword.numeric.ChatScript</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Response control</string>
			<key>match</key>
			<string>#(RESPONSE_UPPERSTART|RESPONSE_REMOVESPACEBEFORECOMMA|RESPONSE_ALTERUNDERSCORES|ALL_RESPONSES|RESPONSE_REMOVETILDE|RESPONSE_CURLYQUOTES)</string>
			<key>name</key>
			<string>constant.language.ChatScript</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Token control</string>
			<key>match</key>
			<string>#(DO_SUBSTITUTE_SYSTEM|DO_ESSENTIALS|DO_SUBSTITUTES|DO_CONTRACTIONS|DO_INTERJECTIONS|DO_BRITISH|DO_SPELLING|DO_TEXTING|DO_NOISE|DO_PRIVATE|DO_NUMBER_MERGE|DO_PROPERNAME_MERGE|DO_DATE_MERGE|NO_PROPER_SPELLCHECK|NO_LOWERCASE_PROPER_MERGE|DO_SPELLCHECK|DO_INTERJECTION_SPLITTING|DO_PARSE|DO_POSTAG|NO_IMPERATIVE|NO_WITHIN|NO_SENTENCE_END|NO_HYPHEN_END|NO_COLON_END|NO_SEMICOLON_END|STRICT_CASING|ONLY_LOWERCASE|TOKEN_AS_IS|SPLIT_QUOTE|UNTOUCHED_INPUT)</string>
			<key>name</key>
			<string>constant.language.ChatScript</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Print output codes</string>
			<key>match</key>
			<string>(?!\w)(#*)(OUTPUT_RAW|OUTPUT_RETURNVALUE_ONLY|OUTPUT_NOCOMMANUMBER|OUTPUT_NOQUOTES|OUTPUT_NOUNDERSCORE)</string>
			<key>name</key>
			<string>constant.language.ChatScript</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>End/nofail codes</string>
			<key>match</key>
			<string>(?!\w)(#*)(NOFAIL|FAIL|CALL|RULE|LOOP|TOPIC|SENTENCE|INPUT|PLAN)</string>
			<key>name</key>
			<string>constant.language.ChatScript</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>TCP open</string>
			<key>match</key>
			<string>(?!\w)(#*)(POST|GET|TRACE_TCP|POSTU|GETU)</string>
			<key>name</key>
			<string>constant.language.ChatScript</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Logs</string>
			<key>match</key>
			<string>(?!\w)(#*)(FILE|OPEN|CLOSE)</string>
			<key>name</key>
			<string>constant.language.ChatScript</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Json</string>
			<key>match</key>
			<string>(?!\w)(#*)(INDEX|VALUE)</string>
			<key>name</key>
			<string>constant.language.ChatScript</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Words</string>
			<key>match</key>
			<string>(?!\w)(#*)(NOUN|VERB|ADJECTIVE|ADVERB|PREPOSITION)</string>
			<key>name</key>
			<string>constant.language.ChatScript</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Facts</string>
			<key>match</key>
			<string>(?!\w)(#*)(direct_s|direct_v|direct_o|direct_sv|direct_so|direct_vo|direct_svo|Unipropogate|FACTDEAD)</string>
			<key>name</key>
			<string>constant.language.ChatScript</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>POS</string>
			<key>match</key>
			<string>(?!\w)(#*)(NOUN|VERB|ESSENTIAL_POS|ADJECTIVE|ADVERB|BASIC_POS|PREPOSITION|ESSENTIAL_FLAGS|CONJUNCTION_COORDINATE|CONJUNCTION_SUBORDINATE|CONJUNCTION|PREDETERMINER|DETERMINER|POSSESSIVE|PRONOUN_POSSESSIVE|POSSESSIVE_BITS|DETERMINER_BITS|COMMA|REQUIRE_CONCEPT|PAREN|PUNCTUATION|QUOTE|CURRENCY|ADJECTIVE_NORMAL|ADJECTIVE_NUMBER|ADJECTIVE_NOUN|ADJECTIVE_PARTICIPLE|ADJECTIVE_BITS|INTERJECTION|THERE_EXISTENTIAL|FOREIGN_WORD|TO_INFINITIVE|NOUN_ADJECTIVE|NOUN_SINGULAR|NOUN_PLURAL|NOUN_PROPER_SINGULAR|NOUN_PROPER_PLURAL|NOUN_GERUND|NOUN_NUMBER|NOUN_INFINITIVE|NOUN_PROPER|NORMAL_NOUN_BITS|NOUN_BITS|VERB_PRESENT|VERB_PRESENT_3PS|VERB_PRESENT_PARTICIPLE|VERB_PAST|VERB_PAST_PARTICIPLE|VERB_INFINITIVE|PARTICLE|VERB_BITS|PRONOUN_SUBJECT|PRONOUN_OBJECT|PRONOUN_BITS|AUX_DO|AUX_HAVE|AUX_BE|AUX_VERB_PRESENT|AUX_VERB_FUTURE|AUX_VERB_PAST|AUX_VERB_TENSES|AUX_VERB|STARTTAGS|AS_IS)</string>
			<key>name</key>
			<string>constant.language.ChatScript</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Other special words</string>
			<key>match</key>
			<string>(?!\w)(#*)(TOPRULES|PENDING|START|END|BOTH|BOT|USER|AUTOSPACE|HAS_SUBSTITUTE|CONCEPT|TOPIC)</string>
			<key>name</key>
			<string>constant.language.ChatScript</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\^(addtopic|available|cleartopics|counttopic|gambit|getrule|hasgambit|keep|lastused|poptopic|refine|rejoinder|respond|retry|reuse|sequence|setrejoinder|topicflags|sleep))(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.ChatScript</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Built-in functions (topics)</string>
			<key>contentName</key>
			<string>variable.ChatScript</string>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>variable.ChatScript</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\^(mark|unmark|position|setposition|marked|setcanon|settag|setoriginal|setrole|savesentence|restoresentence))(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.ChatScript</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Built-in functions (marking)</string>
			<key>contentName</key>
			<string>variable.ChatScript</string>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>variable.ChatScript</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\^(analyze|capitalized|input|isnornalword|original|removetokenflags|settokenflags|setwildcardindex|tokenize))(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.ChatScript</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Built-in functions (input)</string>
			<key>contentName</key>
			<string>variable.ChatScript</string>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>variable.ChatScript</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\^(compute|isnumber|timefromseconds|timeinfofromseconds|timetoseconds))(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.ChatScript</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Built-in functions (number)</string>
			<key>contentName</key>
			<string>variable.ChatScript</string>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>variable.ChatScript</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\^(flushoutput|insertprint|keephistory|lastsaid|print|preprint|repeat|reviseoutput))(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.ChatScript</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Built-in functions (output)</string>
			<key>contentName</key>
			<string>variable.ChatScript</string>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>variable.ChatScript</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\^(response|responsequestion|responseruleid|setresponse))(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.ChatScript</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Built-in functions (output access)</string>
			<key>contentName</key>
			<string>variable.ChatScript</string>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>variable.ChatScript</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\^(postprintbefore|postprintafter))(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.ChatScript</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Built-in functions (print)</string>
			<key>contentName</key>
			<string>variable.ChatScript</string>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>variable.ChatScript</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>System variables (user input)</string>
			<key>match</key>
			<string>(\%)(externaltagging|bot|revisedinput|command|foreign|impliedyou|input|ip|language|length|more|morequestion|originalinput|originalsentence|parsed|question|quotation|sentence|tense|tokenflags|userfirstline|user|userinput|voice|rand)</string>
			<key>name</key>
			<string>constant.numeric.ChatScript</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\^(environment|system|popen|tcpopen|export|import))(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.ChatScript</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Built-in functions (external access)</string>
			<key>contentName</key>
			<string>variable.ChatScript</string>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>variable.ChatScript</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\^(debug|log|memorymark|memoryfree|memorygc|result))(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.ChatScript</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Built-in functions (debugging)</string>
			<key>contentName</key>
			<string>variable.ChatScript</string>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>variable.ChatScript</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\^(jsonarrayinsert|jsonarraydelete|jsoncreate|jsondelete|jsongather|jsonkind|jsonlabel|jsonobjectinsert|jsonopen|jsonwrite|jsonparse|jsonpath|jsontree|jsonarraysize|jsonreadcvs|jsonundecodestring))(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.ChatScript</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Built-in functions (json)</string>
			<key>contentName</key>
			<string>variable.ChatScript</string>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>none.ChatScript</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\^(burst|words|canon|extract|findtext|flags|intersectwords|join|actualinputrange|originalinputrange|properties|pos|decodeinputtoken|decodepos|layer|partofspeech|phrase|role|tally|rhyme|substitute|spell|sexed|uppercase|format|addproperty|define|hasanyproperty|hasallproperty|removeinternalflag|removeproperty|walkdictionary|iterator|wordatindex))(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.ChatScript</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Built-in functions (word manipulation)</string>
			<key>contentName</key>
			<string>variable.ChatScript</string>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>variable.ChatScript</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\^(disable|enable|length|next|pick|reset))(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.ChatScript</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Built-in functions (multipurpose)</string>
			<key>contentName</key>
			<string>variable.ChatScript</string>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>variable.ChatScript</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\^(findfact|query|first|last|sort|delete|nth|unpackfactref|save|addproperty|conceptlist|wordinconcept|createattribute|createfact|writefact|revisefact|field|find|findmarkedfact|flushfacts|gambittopics|intersectfacts|keywordtopics|makereal|pendingtopics|querytopics|removeproperty|unduplicate|uniquefacts))(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.ChatScript</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Built-in functions (facts)</string>
			<key>contentName</key>
			<string>variable.ChatScript</string>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>variable.ChatScript</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\^([\w, \-, \_]+))(?:\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>none.ChatScript</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>User defined functions</string>
			<key>contentName</key>
			<string>none.ChatScript</string>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>variable.ChatScript</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>Print escapes</string>
			<key>match</key>
			<string>(\\[\w,\d,\[,\],\(,$,\-,\+,_]+)|(\\([n,r,t]?))</string>
			<key>name</key>
			<string>string.source.ChatScript</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^s:|^u:|^t:|\?:)\s+([A-Z,\-,\_,\d]*)\s*\((\_?)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.ChatScript</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.other.inherited-class.ChatScript</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.numeric.ChatScript</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Matching rules</string>
			<key>contentName</key>
			<string>none.ChatScript</string>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.numeric.ChatScript</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.source.ChatScript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\*|&lt;&lt;|&gt;&gt;|==|\!\=|\!|\?|\[|\]|\{|\}|\"|\'|&lt;|&gt;|\_(?![a-z]))|(\w|\-|~+)</string>
					<key>name</key>
					<string>keyword.numeric.ChatScript</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>Gambit with no parentesis</string>
			<key>match</key>
			<string>^t:\s</string>
			<key>name</key>
			<string>entity.name.function.ChatScript</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>([a-q]:)\s+([A-Z,\-,\_,\d]*)\s*(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.ChatScript</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.other.inherited-class.ChatScript</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Rejoinder rules</string>
			<key>contentName</key>
			<string>none.ChatScript</string>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.numeric.ChatScript</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.source.ChatScript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\*|&lt;&lt;|&gt;&gt;|==|\!\=|\!|\?|\[|\]|\{|\}|\"|\'|&lt;|&gt;|\_(?![a-z]))|(\w|\-|~+)</string>
					<key>name</key>
					<string>keyword.numeric.ChatScript</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.other.inherited-class.ChatScript</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Invoked rules</string>
			<key>match</key>
			<string>(~[\w,\-,\_]+)\.([A-Z,\-,\_,\d]*)</string>
			<key>name</key>
			<string>none.ChatScript</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Indirect returns/sets</string>
			<key>match</key>
			<string>(\^\".*\")|(\^\$+\w+)</string>
			<key>name</key>
			<string>string.source.ChatScript</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Wildcard operator</string>
			<key>match</key>
			<string>\*\~?\d</string>
			<key>name</key>
			<string>keyword.numeric.ChatScript</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(concept:).*\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.ChatScript</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Concepts</string>
			<key>end</key>
			<string>\)</string>
			<key>name</key>
			<string>none.ChatScript</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>none.ChatScript</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>Describe</string>
			<key>match</key>
			<string>(describe:)</string>
			<key>name</key>
			<string>entity.name.function.ChatScript</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Outputmacro</string>
			<key>match</key>
			<string>(outputmacro:)</string>
			<key>name</key>
			<string>entity.name.function.ChatScript</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Patternmacro</string>
			<key>match</key>
			<string>(patternmacro:)</string>
			<key>name</key>
			<string>entity.name.function.ChatScript</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Dualmacro</string>
			<key>match</key>
			<string>(dualmacro:)</string>
			<key>name</key>
			<string>entity.name.function.ChatScript</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Table</string>
			<key>match</key>
			<string>(table:)</string>
			<key>name</key>
			<string>entity.name.function.ChatScript</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Topic</string>
			<key>match</key>
			<string>(topic:)</string>
			<key>name</key>
			<string>entity.name.function.ChatScript</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Tablemacro</string>
			<key>match</key>
			<string>(tablemacro:)</string>
			<key>name</key>
			<string>entity.name.function.ChatScript</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Data</string>
			<key>match</key>
			<string>(data:)</string>
			<key>name</key>
			<string>entity.name.function.ChatScript</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Rename</string>
			<key>match</key>
			<string>(rename:)</string>
			<key>name</key>
			<string>entity.name.function.ChatScript</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Replace</string>
			<key>match</key>
			<string>(replace:)</string>
			<key>name</key>
			<string>entity.name.function.ChatScript</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Query</string>
			<key>match</key>
			<string>(query:)</string>
			<key>name</key>
			<string>entity.name.function.ChatScript</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Canon</string>
			<key>match</key>
			<string>(canon:)</string>
			<key>name</key>
			<string>entity.name.function.ChatScript</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Plan</string>
			<key>match</key>
			<string>(plan:)</string>
			<key>name</key>
			<string>entity.name.function.ChatScript</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Bot</string>
			<key>match</key>
			<string>(bot:)</string>
			<key>name</key>
			<string>entity.name.function.ChatScript</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\#\#&lt;&lt;)</string>
			<key>comment</key>
			<string>Multiline comments</string>
			<key>end</key>
			<string>(\#\#&gt;&gt;)</string>
			<key>name</key>
			<string>comment.line.number-sign.ChatScript</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Comments</string>
			<key>match</key>
			<string>(\#\s?.*)|(\#!\s?.*)|(\#!x\s?.*)</string>
			<key>name</key>
			<string>comment.line.number-sign.ChatScript</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.top</string>
	<key>uuid</key>
	<string>217a687b-ce56-4078-8034-5b1303f17a77</string>
</dict>
</plist>
