<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>top</string>
		<string>tbl</string>
	</array>
	<key>name</key>
	<string>Chatscript</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Comments</string>
			<key>match</key>
			<string>(\#\s+.*)|(\#!\s+.*)|(\#!x\s+.*)</string>
			<key>name</key>
			<string>comment.line.number-sign.Chatscript</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Control tokens</string>
			<key>match</key>
			<string>#DO_DATE_MERGE|#DO_POSTAG|#DO_PARSE|#DO_CONDITIONAL_POSTAG|#NO_ERASE|#STRICT_CASING|#NO_INFER_QUESTION|#DO_SPELLCHECK|#ONLY_LOWERCASE|#NO_IMPERATIVE|#NO_WITHIN|#NO_SENTENCE_END|#NO_HYPHEN_END|#NO_COLON_END|#NO_SEMICOLON_END|#DO_ESSENTIALS|#DO_SUBSTITUTES|#DO_CONTRACTIONS|#DO_INTERJECTIONS|#DO_BRITISH|#DO_SPELLING|#DO_TEXTING|#DO_SUBSTITUTE_SYSTEM|#DO_INTERJECTION_SPLITTING|#DO_NUMBER_MERGE|#DO_PROPERNAME_MERGE</string>
			<key>name</key>
			<string>keyword.source.Chatscript</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i)(outputmacro:|table:)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.Chatscript</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Close parenteses</string>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.Chatscript</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Open parenteses</string>
					<key>match</key>
					<string>(\()</string>
					<key>name</key>
					<string>support.function.Chatscript</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Intercepts ontologies</string>
					<key>match</key>
					<string>(~+[a-z,A-Z,-,_]\w*\b)|([a-z,A-Z,-,_]\w*\b~(\d+))|([a-z,A-Z,-,_]\w*\b~(\w+))</string>
					<key>name</key>
					<string>entity.other.attribute-name</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Intercepts variables</string>
					<key>match</key>
					<string>(?i)(\^\w*)</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i)concept:|topic:</string>
			<key>comment</key>
			<string>Close parenteses</string>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Open parenteses</string>
					<key>match</key>
					<string>(\()</string>
					<key>name</key>
					<string>entity.other.attribute-name</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Topic Control Flags</string>
					<key>match</key>
					<string>(?i)(Random|NoRandom|Keep|Erase|NoStay|Stay|Repeat|NoRepeat|Priority|Normal|Deprioritize|System|User|NoBlocking|NoPatterns|NoSamples|NoKeys|More|Bot=|bot:|Share)(\s)</string>
					<key>name</key>
					<string>keyword.source.Chatscript</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Intercepts ontologies</string>
					<key>match</key>
					<string>(~+[a-z,A-Z,-,_]\w*\b)|([a-z,A-Z,-,_]\w*\b~(\d+))|([a-z,A-Z,-,_]\w*\b~(\w+))</string>
					<key>name</key>
					<string>entity.other.attribute-name</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>Data</string>
			<key>match</key>
			<string>(?i)data:</string>
			<key>name</key>
			<string>support.function.Chatscript</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.Chatscript</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.source.Chatscript</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Read/Set System Variables</string>
			<key>match</key>
			<string>(?i)(\$)(control_pre|control_main|control_post|botprompt|userprompt|crashmsg|token|abstract|prepass|bot|login|randindex)</string>
			<key>name</key>
			<string>string.single.Chatscript</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.Chatscript</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.source.Chatscript</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Read/Set System Variables 5.31</string>
			<key>match</key>
			<string>(?i)(\$)(cs_prepass|cs_control_pre|cs_control_main|cs_control_post|cs_token|cs_response|cs_crashmsg|cs_abstract|cs_userfactlimit|cs_randindex|db_error|findtext_start|tcpopen_error|document|cs_randindex|bot|login)</string>
			<key>name</key>
			<string>string.single.Chatscript</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.Chatscript</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.source.Chatscript</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>System Variables</string>
			<key>match</key>
			<string>(?i)(%)(date|day|daynumber|fulltime|hour|leapyear|daylightsavings|minute|month|monthname|second|volleytime|time|week|year|rand|bot|revisedinput|command|foreign|impliedyou|input|ip|length|more|morequestion|parsed|question|quotation|sentence|tense|user|userfirstline|userinput|voice|inputrejoinde|lastoutput|lastquestion|outputrejoinder|response|all|document|fact|freetext|freedict|freefact|regression|server|rule|topic|actualtopic|trace|dict|engine|os|script|version)</string>
			<key>name</key>
			<string>string.single.Chatscript</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(([u,s,t,r,\?]:\s*)|([a-q\?]:\s*))(\w*+)(\s*)(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.Chatscript</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>keyword.Chatscript</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>keyword.Chatscript</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>#####Define the last element of the meta-scope#####</string>
			<key>end</key>
			<string>(\))\s*+(?!=(&lt;&lt;)|(&gt;&gt;)|((\[)(\w*)(\]))|(\{)|(\})|(\()|(\))|(\*)|(_\D))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.Chatscript</string>
				</dict>
			</dict>
			<key>name</key>
			<string>rules.complex.Chatscript</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.Chatscript</string>
						</dict>
						<key>10</key>
						<dict>
							<key>name</key>
							<string>keyword.Chatscript</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>keyword.Chatscript</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>keyword.Chatscript</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Intercept brackets and &lt;&lt; &gt;&gt;)</string>
					<key>match</key>
					<string>((&lt;&lt;)|(&gt;&gt;))|((\[)|(\]))|((\{)|(\}))|((\()|(\)))</string>
					<key>name</key>
					<string>string.Chatscript</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.source.Chatscript</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Intercept user variables</string>
					<key>match</key>
					<string>(\$)(\w+)</string>
					<key>name</key>
					<string>string.single.Chatscript</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Intercept booleans that are not touching characters</string>
					<key>match</key>
					<string>(?i)(?&lt;!\w)(null|true|false|and|or)(?&lt;!\w)</string>
					<key>name</key>
					<string>constant.language.Chatscript</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Intercepts ontologies</string>
					<key>match</key>
					<string>(~+[a-z,A-Z,-,_]\w*\b)|([a-z,A-Z,-,_]\w*\b~(\d+))|([a-z,A-Z,-,_]\w*\b~(\w+))</string>
					<key>name</key>
					<string>entity.name.class</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Intercept wildcards char and values</string>
					<key>match</key>
					<string>(\*~?\d?)</string>
					<key>name</key>
					<string>keyword.source.Chatscript</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Intercept words with wildcards</string>
					<key>match</key>
					<string>\w+(\*)\w+</string>
					<key>name</key>
					<string>string.Chatscript</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.source.Chatscript</string>
						</dict>
						<key>9</key>
						<dict>
							<key>name</key>
							<string>constant.other.Chatscript</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Intercept conditionals</string>
					<key>match</key>
					<string>((!=)|(&gt;=)|(&lt;=)|(&gt;)|(&lt;)|(==)|(=))((\d+)|(\w+))</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Intercept &lt;,&gt;,!,?,&amp;,~</string>
					<key>match</key>
					<string>(&lt;)|(&gt;)|(!)|(\?)|(&amp;)|(~\s)|(_)|(\\)</string>
					<key>name</key>
					<string>keyword.Chatscript</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Intercept digits</string>
					<key>match</key>
					<string>\s([\d])+</string>
					<key>name</key>
					<string>constant.other.Chatscript</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Everything unmatched at this point is likely words to intercepts so we match '.'</string>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>string.Chatscript</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>((if)|(else if))\s?(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.source.Chatscript</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.Chatscript</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Intercept if/else if statement</string>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.Chatscript</string>
				</dict>
			</dict>
			<key>name</key>
			<string>rules.complex.Chatscript</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.source.Chatscript</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.other.Chatscript</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Conditions and operators</string>
					<key>match</key>
					<string>(?i)(!=|&gt;=|&lt;=|&gt;|&lt;|==)|(and|or)|(!)</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.source.Chatscript</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Intercept else statement and opening brackets separately</string>
			<key>match</key>
			<string>((else) (\{))|(\{)|(\})|(\[)|(\])</string>
			<key>name</key>
			<string>keyword.Chatscript</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Intercept variable assignements</string>
			<key>match</key>
			<string>(\s?)((\+=)|(-=)|(\*=)|(/=)|(%=)|(\|=)|(&amp;=)|(\^=)|((?&lt;!=)=(?!=)))</string>
			<key>name</key>
			<string>variable.parameter</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Intercept gambits without user input</string>
			<key>match</key>
			<string>(^([t,r,\?]:)\s*)</string>
			<key>name</key>
			<string>keyword.source.parameter</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Intercept @digit</string>
			<key>match</key>
			<string>@(\d+)</string>
			<key>name</key>
			<string>constant.other.Chatscript</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Intercept digits</string>
			<key>match</key>
			<string>\s?(\d)+|(?i)null</string>
			<key>name</key>
			<string>constant.other.Chatscript</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.Chatscript</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.source.Chatscript</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.function.Chatscript</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Intercept user variables outside of rules</string>
			<key>match</key>
			<string>(_?)(\${1,2})(\w+)</string>
			<key>name</key>
			<string>string.single.Chatscript</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.Chatscript</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.Chatscript</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Intercept match variables</string>
			<key>match</key>
			<string>('?_)(\d+)</string>
			<key>name</key>
			<string>string.single.Chatscript</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>entity.name.class</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Intercepts ontologies outside of regular match rules</string>
			<key>match</key>
			<string>((~+[a-z,A-Z,-,_]\w*\b)|([a-z,A-Z,-,_]\w*\b~(\d+))|([a-z,A-Z,-,_]\w*\b~(\w+)))(\.?)([A-Z]*)</string>
			<key>name</key>
			<string>entity.name.class</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i)(\^?)(addtopic|available|cleartopics|counttopic|gambit|getrule|hasgambit|keep|lastused|next|poptopic|refine|rejoinder|respond|retry|reuse|setrejoinder|topicflags)(\s?\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.Chatscript</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.source.Chatscript</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.Chatscript</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Topic Functions</string>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.Chatscript</string>
				</dict>
			</dict>
			<key>name</key>
			<string>rules.complex.Chatscript</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>support.other.variable</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i)(\^?)(mark|unmark|marked|position|setposition)(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.Chatscript</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.source.Chatscript</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.Chatscript</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Marking Functions</string>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.Chatscript</string>
				</dict>
			</dict>
			<key>name</key>
			<string>rules.complex.Chatscript</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>support.other.variable</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i)(\^?)(analyze|capitalized|input|position|removetokenflags|settokenflags|setwildcardindex)(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.Chatscript</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.source.Chatscript</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.Chatscript</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Input Functions</string>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.Chatscript</string>
				</dict>
			</dict>
			<key>name</key>
			<string>rules.complex.Chatscript</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>support.other.variable</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i)(\^?)(compute|timefromseconds|timeinfofromseconds|timetoeconds)(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.Chatscript</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.source.Chatscript</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.Chatscript</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Number Functions</string>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.Chatscript</string>
				</dict>
			</dict>
			<key>name</key>
			<string>rules.complex.Chatscript</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>support.other.variable</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i)(\^?)(flushoutput|insertprint|keephistory|lastsaid|print|preprint|repeat|reviseOutput)(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.Chatscript</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.source.Chatscript</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.Chatscript</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Output Functions</string>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.Chatscript</string>
				</dict>
			</dict>
			<key>name</key>
			<string>rules.complex.Chatscript</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>support.other.variable</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i)(\^?)(response|responsequestion|responseruleid)(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.Chatscript</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.source.Chatscript</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.Chatscript</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Output Access</string>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.Chatscript</string>
				</dict>
			</dict>
			<key>name</key>
			<string>rules.complex.Chatscript</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>support.other.variable</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i)(\^?)(postprintbefore|postprintafter)(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.Chatscript</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.source.Chatscript</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.Chatscript</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>PostProcessing Functions</string>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.Chatscript</string>
				</dict>
			</dict>
			<key>name</key>
			<string>rules.complex.Chatscript</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>support.other.variable</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i)(\^?)(argument|command|end|eval|fail|loop|match|nofail|notnull|addcontext|incontext)(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.Chatscript</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.source.Chatscript</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.Chatscript</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Control Flow Functions</string>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.Chatscript</string>
				</dict>
			</dict>
			<key>name</key>
			<string>rules.complex.Chatscript</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>support.other.variable</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i)(\^?)(burst|explode|extract|findtext|flags|intersectwords|join|properties|pos|decodepos|partofspeech|role|tally|rhyme|substitute|spell|sexed|uppercase|addproperty|define|hasproperty|hasallproperty|hasanyproperty|properties|removeinternalflag|removeproperty|walkdictionary|Iterator)(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.Chatscript</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.source.Chatscript</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.Chatscript</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Word Manipulation Functions</string>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.Chatscript</string>
				</dict>
			</dict>
			<key>name</key>
			<string>rules.complex.Chatscript</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>support.other.variable</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i)(\^?)(disable|enable|length|pick|reset)(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.Chatscript</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.source.Chatscript</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.Chatscript</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Multipurpose Functions</string>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.Chatscript</string>
				</dict>
			</dict>
			<key>name</key>
			<string>rules.complex.Chatscript</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>support.other.variable</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i)(\^?)(FindFact|query|first|last|pick|sort|nth|Unpackfactref |AddProperty|conceptlist|Createattribute|createfact|revisefact|delete|field|find|Output|findmarkedfact|first|flushfacts|gambittopics|intersectfacts|keywordtopics|last|length|makereal|next|pendingtopics|pick|queryTopics|RemoveProperty|reset|query|save|sort|unduplicate|uniquefacts|unpackfactref)(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.Chatscript</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.source.Chatscript</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.Chatscript</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Facts Functions (see ChatScript Fact Manual)</string>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.Chatscript</string>
				</dict>
			</dict>
			<key>name</key>
			<string>rules.complex.Chatscript</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>support.other.variable</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.top</string>
	<key>uuid</key>
	<string>217a687b-ce56-4078-8034-5b1303f17a77</string>
</dict>
</plist>
